/control/verbose 0
/run/verbose 1
/tracking/verbose 0

/spect/output/file ../output/spect_vis_tracks.root

/gps/particle gamma
/gps/pos/type Point
/gps/pos/centre 0 0 -120 mm
/gps/ang/type iso
/gps/ene/type Mono
/gps/ene/mono 140.5 keV

/vis/open VRML2FILE
/vis/viewer/set/autoRefresh false
/vis/verbose warnings
/vis/drawVolume
/vis/scene/add/axes 0 0 -120 10 mm

/vis/scene/add/trajectories rich smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ cyan

/vis/filtering/trajectories/create/encounteredVolumeFilter
/vis/filtering/trajectories/encounteredVolumeFilter-0/add LSO_phys
/vis/scene/endOfEventAction accumulate -1

/run/beamOn 10000

/vis/viewer/flush
